# Convenience shortcuts for common developer tasks.
#
# This is just a thin wrapper so you don't have to remember the full
# ``sphinx-build`` invocation. Run these from the repository root:
#
#   make docs        -- build the HTML documentation once into docs/_build/html
#   make docs-live    -- live preview: rebuild + refresh the browser on every save
#   make docs-clean   -- delete the generated docs (docs/_build)
#   make docs-strict  -- build the way CI/Read the Docs does (warnings are errors)
#
# First-time setup (installs Sphinx + the theme + extensions):
#
#   pip install -e ".[docs]"

# Where the docs sources live and where the built site goes.
DOCS_SRC   = docs
DOCS_OUT   = docs/_build/html

.PHONY: docs docs-live docs-clean docs-strict

## Build the docs once, then tell you where to open them.
docs:
	sphinx-build -b html $(DOCS_SRC) $(DOCS_OUT)
	@echo ""
	@echo "Docs built. Open: $(DOCS_OUT)/index.html"

## Live preview: watches docs/ and primat/ and auto-refreshes the browser.
## Needs sphinx-autobuild (included in the "docs" extra). Serves at the URL it
## prints, usually http://127.0.0.1:8000 -- leave it running while you edit.
docs-live:
	sphinx-autobuild $(DOCS_SRC) $(DOCS_OUT) --open-browser --watch primat

## Same strict build CI and Read the Docs run: any warning fails the build.
docs-strict:
	sphinx-build -W --keep-going -b html $(DOCS_SRC) $(DOCS_OUT)

## Remove the generated site (safe: it is regenerated by any build above).
docs-clean:
	rm -rf docs/_build
